### ISSUE TITLE
[Quest] The Demons Below

### ISSUE THREAD

**Issue by Spydoc** [Mike-SPP/Project-Aurora#116]
Medium issue:

The quest The Demons Below should be available after completing the quest Awakening the Archdruid.

https://www.wowhead.com/quest=38144/the-demons-below
https://www.wowhead.com/quest=38143/awakening-the-archdruid

**Comment by sausagemadness** [comment]
The quest is available and completable

**Comment by sausagemadness** [comment]
Kamino cloned this issue to [Project-AuroraWoW/Project-Aurora-Bug-Tracker](https://github.com/Project-AuroraWoW/Project-Aurora-Bug-Tracker/issues/146)
