### ISSUE TITLE
[Quest] Entangled Dreams

### ISSUE THREAD

**Issue by Spydoc** [Mike-SPP/Project-Aurora#123]
Medium issue:

The quest Entangled Dreams should be available after completing the two quests The Demons Below and Out of the Dream.

https://www.wowhead.com/quest=38147/entangled-dreams

**Comment by sausagemadness** [comment]
The quest is available and completable

**Comment by sausagemadness** [comment]
Kamino cloned this issue to [Project-AuroraWoW/Project-Aurora-Bug-Tracker](https://github.com/Project-AuroraWoW/Project-Aurora-Bug-Tracker/issues/153)
