### ISSUE TITLE
[Quest] Malfurion's Fury

### ISSUE THREAD

**Issue by Spydoc** [Mike-SPP/Project-Aurora#128]
Medium issue:

The quest Malfurion's Fury should be available after completing the quest The Die is Cast.

https://www.wowhead.com/quest=38595/malfurions-fury

**Comment by sausagemadness** [comment]
The quest Malfurion's Fury is available and completable.

**Comment by sausagemadness** [comment]
Kamino cloned this issue to [Project-AuroraWoW/Project-Aurora-Bug-Tracker](https://github.com/Project-AuroraWoW/Project-Aurora-Bug-Tracker/issues/158)
