### ISSUE TITLE
Mildred the Cruel

### ISSUE THREAD

**Issue by Senjah** [Mike-SPP/Project-Aurora#220]
https://www.wowhead.com/quest=12905/mildred-the-cruel
Mildred the cruel npc is enemy npc not friendly as intented

**Comment by Duff-SPP** [comment]
Simple Flag change from Enemy To Friendly

**Comment by sausagemadness** [comment]
Closing this issue as completed.

**Comment by sausagemadness** [comment]
Kamino cloned this issue to [Serithul/Project-Aurora-Bug-Tracker](https://github.com/Project-AuroraWoW/Project-Aurora-Bug-Tracker/issues/250)
